### ISSUE TITLE
License enforcement

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/gluu-gateway#1]
This is licensed software available for use by Gluu support customers. 

We need to enforce a license check before allowing a user to proceed with using the software. During license enforcement, we must confirm that the license's `product parameter` includes `api_gateway`.

**Comment by willow9886** [comment]
See: https://github.com/GluuFederation/oxLicense/issues/19

**Comment by yurem** [comment]
I think this process should looks like this:
1. Install package. We can allow to install it because without license they should not work
2. Run installer
3. Asks for license file. If we have API to parse it we can check if there is license to access this component. If there is no this API we can use license server to check it
4. Finish install

@yuriyz Can you review this and give more details?

**Comment by yuriyz** [comment]
Installer should ask for license details means: license_id, public_key, public_password, license_password.
Those details are typically expected to be in configuration file. So admin/user can always revisit and correct those details. Enforcement of the license has to be performed at runtime. 
Here is example how it is implemented for oxd:

- https://github.com/GluuFederation/oxd/blob/5b5c97e2d8b8e724908ca8a2e3bef0435f741b3e/oxd-server/src/main/java/org/xdi/oxd/server/license/LicenseFileUpdateService.java#L32-32
- https://github.com/GluuFederation/oxd/blob/3e14acd27c6ce218247b8e90e2dd504e5f6d3023/oxd-server/src/main/java/org/xdi/oxd/server/license/LicenseService.java#L40-40

We have ready to go `LicenseValidator` on java, so validation is trivial. If license is valid you can get license metadata. Among other information there is `products` json key which contains set of products to which this license is allowed. Gluu Gateway must check that `api_gateway` value is present in `products` set.

As far as I remember Shouro was not able to use java directly, so he use this runnable jar which accepts difference parameters and as result prints license metadata if license is valid or otherwise print exception stacktrace.

The jar is here:
http://ox.gluu.org/maven/org/xdi/oxlicense-validator/3.2.0-SNAPSHOT/oxlicense-validator-3.2.0-SNAPSHOT-jar-with-dependencies.jar

Below you can see what each parameter means
```
public class LicenseValidatorExecutor {

    private static final String ARGUMENTS_MESSAGE = "java org.xdi.oxd.license.validator.LicenseValidatorExecutor " +
            "<license> <public key> <public password> <license password> <product (de, oxd)> <current date as milliseconds>";

    /**
     * Required by Docker Edition.
     *
     * @param args args
     * @throws IOException
     */
    public static void main(String[] args) throws IOException {
        System.out.println("Validator expects: " + ARGUMENTS_MESSAGE);
        Preconditions.checkArgument(args.length == 6, "Please specify arguments for program as following: " + ARGUMENTS_MESSAGE);

        String license = args[0];
        String publicKey = args[1];
        String publicPassword = args[2];
        String licensePassword = args[3];
        String product = args[4];
        String currentDate = args[5];

        LicenseContent licenseContent = LicenseValidator.validate(publicKey, publicPassword, licensePassword, license, Product.fromValue(product), new Date(Long.parseLong(currentDate)));

        System.out.println(Jackson.asJsonSilently(licenseContent));
    }

}
```
