### ISSUE TITLE
Add Grafana Graphs

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#124]
It would be great if we could generate graphs in Grafana
https://grafana.com/

**Comment by ldeveloperl1985** [comment]
@nynymike I've studied Grafana. But it has some limitation.
1. We required extra setup for that because is not javascript chart library to include in GG. It has .deb installation, log in and starting as a server.

Instead of this, I purpose to use an existing tool of GG. we already have a [dashboard](https://prnt.sc/jlh8xv) with [Char.js](http://jtblin.github.io/angular-chart.js/) feature.

Agree?

**Comment by nynymike** [comment]
I think we should maybe have some very simple graphs in GG GUI. But we should think about Grafana. People are using this tool anyway. We don't have to include it in our GG package. But we can include instructions separately on how to configure it, and what kind of graphs are available.  Remember, GG is just one tool of many at an organization.

**Comment by ldeveloperl1985** [comment]
Done.
Added instruction in docs https://gluu.org/docs/gg/plugin/gluu-metrics/
