### ISSUE TITLE
Configuration of gluu-oauth2-client-auth plugin

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#194]
Hi, sorry if I would ask some stupid questions here, I'm still newbie here.

The plugin configuration looks as below:
- create API (will be changed to Service/Route(s) soon, will use API term for simplicity)
- enable plugin for API 
- create some Kong consumers
- Create OAuth credential https://github.com/GluuFederation/gluu-gateway/tree/master/gluu-oauth2-client-auth#create-a-consumer

The past one is most interesting.

It creates a new customer on authorization server (Gluu-server) and associate it with Kong consumer.
Also it is possible to associate existing customer with Kong consumer.

Another important thing - it assign to a customer a plugin processing mode.

Relevant chat discussion:

>  Alexander Altshuler @altshuler gluu 6:09 PM
> we associate mode (oauth, uma, mix) with user credential, IMO usually one api has consistent auth. policy. is it by design?
> 
> Michael Schwartz @nynymike admin gluu 6:40 PM
> A client must be declared as oauth or uma, because we validate and cache the token, and the client may subsequently call many APIs
> 
> Hypothetically, an API could use both OAuth and UMA, although in practice, it’s probably one or the other…

Current code do the following:
- try to call introspect_access_token() API, if OK - the token is OAuth token
- otherwise call introspect_rpt() API, if OK - the token is UMA RPT.
- upon succesfull introspection we know a customer
- check does token correspond to the mode for this customer

I don't understand  your @nynymike  sentence below:
> A client must be declared as oauth or uma, because we validate and cache the token,

For me more intuitive would be to configure the API for possible modes.
Example configurations:
- the API should accept  OAuth access tokens, no UMA
- the API should accept  OAuth access tokens, but works in mix mode
- the API should accept UMA RPT

If customer is associated with consumer and have valid active token it must be authorized.

It also allows exotic both-AOuth-UMA use case.

What is the important from plugin internal point of view that plugin mode(s) will be configured on
API/plugin level and will be directly accessed as config without any db access.

Another thing which may be configured for a customer is restrict_api/restrict_api_list.
BTW it is not documented.
As I understand from the source code it is restrict the customer to use some APIs.

IMO For this task we shall use existing Kong ACL plugin.
It works after authentication plugin within Kong plugin chain and does exactly this task.
We break the _single point of responsibility_ principle assigning this task to our OAuth plugin.

**Comment by ldeveloperl1985** [comment]
@altexy I think, you need to take first look at the plugin OAuth flow and UMA flow.

You can copy and paste text in `websequencediagrams.com` for sequence flow UI diagram.
1. Plugin configuration https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.3.1/doc/sequence_diagram-config
2. gluu-oauth2-client plugin access phase https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.3.1/doc/sequence_diagram-oauth-consumer
3. gluu-oauth3-rs plugin access phase https://github.com/GluuFederation/gluu-gateway/blob/version_3.1.3.1/doc/sequence_diagram_uma_rs

Detail of UMA flow: https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html

Q.  it is possible to associate existing customer with Kong consumer?
--> Yes, You can enter existing client credential in [create-an-oauth-credential](https://www.gluu.org/docs/gg/3.1.3/plugin/api/#create-an-oauth-credential) process.

Q. A client must be declared as oauth or uma, because we validate and cache the token
-->
> Note: As per my understanding your comment. customer is equal to the client(word used by mike). Called it as a client not customer.

1. If introspect_access_token() successful, then your client is OAuth client
    If introspect_rpt() successful, then your client is UMA client
2. RS plugin depend on OAuth plugin. Introspection done by OAuth plugin and set cache. Same cache is used in RS plugin.


Q.  Kong ACL plugin?
-->
There is a document for restrict_api: https://www.gluu.org/docs/gg/3.1.3/plugin/api/#create-an-oauth-credential

Kong ACL plugin is Consumer level. But the requirement is, control it by Consumer clients. If we set it to the consumer then it disables for all the clients. So to control API from every separately Client it good idea.

**Comment by altshuler** [comment]
Hello, 

I think my mail was attached by mistake to this conversation.

Please remove me from your mail list

 

 

Evgeny

**Comment by nynymike** [comment]
This is not a support forum. Please register and raise any questions about the Gluu Gateway on https:/support.gluu.org 

You can find docs for GG at : https://gluu.org/docs/gg/3.1.3/
