### ISSUE TITLE
OpenID client names should be descriptive

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#29]
![image](https://user-images.githubusercontent.com/3717101/35783329-e56cbd6e-09ca-11e8-826f-47b54b933739.png)

These clients have different purposes? Why are they both called **konga_client**. Names like this should always be descriptive.

**Comment by ldeveloperl1985** [comment]
We are using oxd-https and it always creates two clients. Both have the same purpose for authentication to KONGA. So *konga_client* name is ok or not?

**Comment by yuriyz** [comment]
Purpose is not the same, `setup_client` command returns:
1. client 1 - setup client used for protection access token (client_id/client_secret)
2. client 2 - oxd_id, regular client that can be used for oxd commands.
Note: that we scheduled to drop `client 2` for next oxd release because it seems to confuse people a lot. 
https://github.com/GluuFederation/oxd/issues/141

**Comment by ldeveloperl1985** [comment]
@nynymike , If is this ok then please close it or give me the name as you want?

**Comment by nynymike** [comment]
If you can combine these clients into one, then there is no need to rename. I'll close this issue for now.
