### ISSUE TITLE
Support Phantom Token Flow

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#317]
In this flow, the client presents an bearer token, but the gateway, post-introspection, replaces the bearer token with a JWT, which it passes to the upstream API. The JWT is not signed because GG is trusted. The client cannot pass any JWT as the bearer token, because it would not be validated. 

The advantage of this is that the bearer token is used on the internet, and the value token on the private network.

**Comment by altexy** [comment]
@nynymike OAuth2 bearer token doesn't have `value of the token`.
We may replace the token with base64 encoded data returned by introspection, below is the example from oxd docs:
```
    "data":{
        "active": true,
        "client_id": "l238j323ds-23ij4",
        "username": "John Black",
        "scopes": ["read", "write"],
        "token_type":"bearer"
        "sub": "jblack",
        "aud": "l238j323ds-23ij4",
        "iss": "https://as.gluu.org/",
        "exp": 1419356238,
        "iat": 1419350238,
        "acr_values": ["basic","duo"],
        "extension_field": "twenty-seven",
        ...
    }
```

We may use JWT as a bearer token, JWT does have JSON value, it is base64 encoded and already available for anybody.

**Comment by altexy** [comment]
4:06 PM @nynymike 
I’m not suggesting that GG sign the JWT.

You can use alg None and then there is nothing after the final . in the JWT

There is no need for GG to sign the token, because it is proxying, the headers are secure, and the JWT can be trusted.



Meghna Joshi @ldeveloperl1985 
gluu 9:40 PM
Agreed 👍


Alexander Altshuler @altexy 
gluu 12:17 PM
ok, we will replace Oauth/RPT tokens (if it is not already JWT) to JWT with alg = none and payload as data filed from introspection response.
We have hide credentials flag, IMO we need once more phantom token which is mutual exlusive with hide credentials flag.

So we will have next choices:
- pass Authorization header as is to upstream
- remove Authorization header
- replace with phantom token

Michael Schwartz @nynymike
gluu12:19 PM
right… I agree that phantom tokens should be configurable.

**Comment by ldeveloperl1985** [comment]
Done and merged into **version_2.0**
