### ISSUE TITLE
Konga with Kong 1.3

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway#359]
Need to research:
- it is possible
- ETA

**Comment by altexy** [comment]
https://github.com/pantsel/konga#compatibility 

> From 0.14.0 onwards, Konga is ONLY compatible with Kong >= 1.0.0

My experience with Kong 1.x shows very good version compatibility.

**Comment by ldeveloperl1985** [comment]
I've checked the Kong changelog from >= 0.15, the estimation is as given below.

## GG Admin UI Estimate
1. All gluu plugins configuration - need to pass a string instead of JSON
2. Kong Upstreams, Targets configurations https://github.com/Kong/kong/blob/master/CHANGELOG.md#admin-api-7
3. Tags update the every kong object(Services, Routes, plugin, ...) configuration - https://github.com/Kong/kong/blob/master/CHANGELOG.md#admin-api-3, https://github.com/Kong/kong/blob/master/CHANGELOG.md#core-8 

**Estimate time: 3 days**
**Note: I've also tested the latest `Pantsel Konga` which is not updated with 3rd point. it is not covering the changes for Kong >= 1.1 . it has only up to Kong 1.0**

## GG Docs Estimate
1. Need to updated every plugin configuration
**Estimate time: 2 days**

## GG Setup script update & packaging & testing
1. Need to update kong configurations
**Estimate time: 2 days**

-------------------------------------------------------------

Total around **7 days** need to cover changes.

**Comment by ldeveloperl1985** [comment]
so, please suggest @altexy @willow9886 , do we want to add it to **GG 4.0**? or in a **future release**?

**Comment by willow9886** [comment]
GG 4.0 @ldeveloperl1985

**Comment by ldeveloperl1985** [comment]
Okay, Thank you, William, I'll start work on it and try to finish ASAP.

**Comment by ldeveloperl1985** [comment]
Tested Konga UI and plugins with the latest GG package, all the things working good. All the test cases passed successful, [Check here for Test case report](https://github.com/GluuFederation/gluu-gateway/wiki/Testing). 

Note: Currently working on GG docs.

**Comment by ldeveloperl1985** [comment]
Done. Docs updated https://gluu.org/docs/gg
