### ISSUE TITLE
Use Gluu Server extension pack for installation

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/gluu-gateway#57]

**Comment by jgomer2001** [comment]
We need to centralize the mechanism used to deliver additional gluu products

Currently we are using the "[Extension pack](https://github.com/GluuFederation/community-edition-setup/wiki/Gluu-Server-CE-Builds#gluu-server-ext-releases)" for [credential manager](https://gluu.org/docs/creds/administration/installation/). So we should include GG in this extension bundle as well.

As of today the bundle comes with this [file](https://github.com/GluuFederation/post-installation-setup/blob/master/setup_cred_mgr.py) which triggers the installation process.  In my opinion it might have a better name like `setup_extensions` or so, but the idea is that we should include the installation logic of products inside such a script if possible, or in the worst create a separate script for the product.  

In this [line](https://github.com/GluuFederation/post-installation-setup/blob/master/setup_cred_mgr.py#L339) we are prompting the user whether he wants to install cred manager, ideally there should be a prompt for GG as well.

As an example the physical bundle already contains some files cred-manager needs (e.g. oxd, some libs, etc.). GG may take advantage of that and also include their own.

@yurem do you still agree with the original idea of standardizing the installation process in a single point? if so, maybe you can depict some roadmap to achive the goal?

**Comment by ldeveloperl1985** [comment]
Questions
1. setup_cred_mgr.py is run inside of chroot but GG’s [setup-gluu-gateway.py](https://github.com/GluuFederation/gluu-gateway/blob/master/setup/setup-gluu-gateway.py) script not requires chroot. it is an independent script.
2. After GG installation, it uses 443 port for the proxy endpoint that creates a problem because gluu server is already run on 443.

**Comment by yurem** [comment]
@willow9886 and @jgomer2001 GG is an independent product which requires same 443 port for proper work. I think we can't put it into extension pack because it depends on CE now.
What we really can TODO is to write universal oxd setup script. And GG and extension pack can run it to unify installation procedure. Example:
```
oxd-setup,py --home ... -- conf ... -- license ... etc.
```

After running it should return exit code 0 or -1 to indicate if there is installation issues.

This should reduce GG and extension pack installation code size.

**Comment by willow9886** [comment]
@yurem this seems reasonable to me...

**Comment by yurem** [comment]
I think we can close this issue and open another one about oxd installation script. From my point of view it's only one reusable part.

GG has an independed setup script which.
Ext pack (Cred manager) uses CE script. It calls setup.py methods.
Hence botch scripts are very different.

 @jgomer2001 What do you think?

**Comment by jgomer2001** [comment]
@yurem I agree with you
