### ISSUE TITLE
Add SECURITY for OAuth Scopes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-gateway#64]
In OAuth-mode, the admin can specify which scopes are required--exactly as in UMA.  The `scopes` claim may be present in Oauth token introspection response JSON. 

For example, a person authorizes a client access token for the `calendar` scope.  Using the Konga UI, the admin can set a policy that requires the `calendar` scope to call an upstream api.

Note: UMA scopes are different then OAuth scopes.

**Comment by ldeveloperl1985** [comment]
For this, I am going to do below step 

step 1. Allow admin to specify the claim scopes in OAuth client creation. example: email, profile, openid, calendar

![oauth_scope](https://user-images.githubusercontent.com/2329776/38491809-9cb5b43c-3c0a-11e8-8679-d78a904e1d61.png)

step 2. After introspection, check the scope return in the response to introspection example: {email,openid} with admin specified scope example {email, profile, openid, calendar}.

step 3. If all the scope of introspection response is available in admin specified scope then allow otherwise 401/Unauthorized

**Comment by nynymike** [comment]
The problem with this is that it's not clear what is the logical operator... is it `(&(email)(openid))` or `(|(email)(openid))`   How would you specify a more complex logical operator? And what if the API has sub-folders which require different scopes. For this reason, I think we can handle the requirement in the same way as we assign UMA scope requirements.

**Comment by kirankdmmali** [comment]
Ok, 
1. Overall you want to put same Uma scope_expression(SECURITY LINK section) thing in OAuth scope. Right?
2. In konga UI, where do we need to add this section for oauth_scope_expression? whether in "OAuth2 client authentication section of the consumer configuration" or any other place? If yes then please make one simple wireframe design so I will get idea how to design the page for this complex logical expression?

**Comment by ldeveloperl1985** [comment]
Ok,

1. Overall you want to put same Uma scope_expression(SECURITY LINK section) thing in OAuth scope. Right?
2. In konga UI, where do we need to add this section for oauth_scope_expression? whether in "OAuth2 client authentication section of the consumer configuration" or any other place? If yes then please make one simple wireframe design so I will get idea how to design the page for this complex logical expression?

**Comment by ldeveloperl1985** [comment]
Done.

Configuration step

1. Configure OAuth scope expression in security link section

![oauthscopeexpression](https://user-images.githubusercontent.com/2329776/39295516-432b1ed4-495c-11e8-9c63-8ef4adca7ebd.png)

2. Enable and disable scope security using flag in OAuth consumer section

![oauthscopeexpressionflag](https://user-images.githubusercontent.com/2329776/39295570-5d1da2a8-495c-11e8-9b1b-efcea66ef2f3.png)

3. At the runtime, it checks the scope of the token(After introspection of the token). If it is matched with scope expression then allow the required otherwise denied.

Example:

OAuth scope expression:
![oauthscopeexpressionexample](https://user-images.githubusercontent.com/2329776/39295985-6587eb96-495d-11e8-9848-34f32fbeb1b2.png)

If requested token has scopes ["openid", "clientinfo"] then request is allowed otherwise denied.

**Comment by natt-tester** [comment]
I think there's something amiss still; there are 400 errors visible -- please refer to the gif. When I try to add security to both UMA and OAUTH, clicking ADD sends me to the previous screen, but there's nothing changed when I click SECURITY.
![2018-04-27_20h30_43](https://user-images.githubusercontent.com/38302725/39359153-22247ee6-4a5c-11e8-910d-6b0edcb19928.gif)

**Comment by ldeveloperl1985** [comment]
link to https://github.com/GluuFederation/gluu-gateway/issues/82
